### ISSUE TITLE
Enforce programs to be 1 -> 1

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#105]
There should be an explicit program type that enforces the contained expression to be of type `1 → 1`.

One idea is to check this in `CommitNode::finalize()`. There could be a check just for `1 → 1` and a separate method for adding witness data.

What would be use cases of `RedeemNode`s of different types?

**Comment by apoelstra** [comment]
I think this has been resolved with the node overhaul; now `ContructNode::decode` is a free-for-all but `CommitNode::decode` and `RedeemNode::decode` enforce 1-1ness.
