### ISSUE TITLE
Value debug + display

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#106]
Errors related to Simplicity values are hard to debug because of the way that values are printed. If a value is a power of two, it should print a hex string. If it is a nested pair of bits, it should print a bit string. Sums and products of the above can be printed as so.

**Comment by uncomputable** [comment]
d98bfc95de5749e271a3b146add81b9b70086769 adds a bit representation of values. We could still handle byte strings or non-standard values like products of units better, but I will close this issue for now.

**Comment by apoelstra** [comment]
I think we should eventually represent values as byte vectors along with a `types::Final`. Then when we need to destructure the value (not too often) we can recursively do so with the type ... and for display purposes it will be easy to TMR-match to recognize powers of 2.

Not sure if we should re-open this issue to track that or open a new one.
