### ISSUE TITLE
Support option types

### ISSUE THREAD

**Issue by roconnor-blockstream** [BlockstreamResearch/rust-simplicity#157]
I use 'S A' in the tech-report for the option type.  The idea is that 'S' is shorthand for 'successor', which in turn means 'plus one'.  However feel free to use whatever syntax you are most comfortable with.  The above is a little bit obtuse.

**Comment by uncomputable** [comment]
Good idea. This would enable us to better handle the source and target types of the sha256 jets, which are pretty wild. There are a lot of other use cases.

**Comment by apoelstra** [comment]
My thoughts are:

* `Option[type]` which I think would be easier to read
* `type?` which is easier to write and continues in the "type constructors are one character" pattern we've had so far

**Comment by roconnor-blockstream** [comment]
`?` is so good (it means + 1 in regexp, or + ε, where ε is basically regexp's notion of 1 (it is a unit of multiplication, which is concatenation)), I feel like I should change my tech report to this symbol.
