### ISSUE TITLE
For the C code we need to turn on the PRODUCTION flag to remove all the frame alignment assertions within the main evaluation loop.

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/rust-simplicity#165]
@apoelstra For the C code we need to turn on the PRODUCTION flag to remove all the frame alignment assertions within the main evaluation loop.

_Originally posted by @roconnor-blockstream in https://github.com/BlockstreamResearch/simplicity/issues/164#issuecomment-1656314963_

**Comment by roconnor-blockstream** [comment]
We also need to the PRODUCTION flag enabled when performing benchmarks.  OTOH, we want the flag off when running the fuzzer.
