### ISSUE TITLE
Infinite finalization loop

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#177]
If I try to decode the bytes of the program `case (drop iden) iden` from the [occurs check test](https://github.com/BlockstreamResearch/simplicity/blob/69eb1719b6a13a4346abde9b221eebc99002cc6f/C/test.c#L278), the binary gets stuck at the line that does the decoding.

```
let program_bytes = vec![0xc1, 0x07, 0x20, 0x30];
let mut bits = simplicity::BitIter::new(program_bytes.iter().copied());
let program = simplicity::CommitNode::<simplicity::jet::Core>::decode(&mut bits).expect("decode");
/// This is never printed
println!("{}", program.cmr());
```

**Comment by apoelstra** [comment]
The infinite loop in your initial case is just the `expect` running on a program whose input type is not unit, but is infinite. It loops forever trying to print the non-unit type in the error.

As near as I can tell, the same issue happens with your other test case.

**Comment by apoelstra** [comment]
Unfortunately the infinite loop that I am encountering is different from these.
