### ISSUE TITLE
windows compilation failures 

### ISSUE THREAD

**Issue by delta1** [BlockstreamResearch/rust-simplicity#186]
hey there 

trying to compile this on windows via github actions is failing, making an issue here for visibility and tracking. 

the issues originate upstream in [BlockstreamResearch/simplicity](/BlockstreamResearch/simplicity)

github actions job showing initial compilation failure: https://github.com/delta1/rust-simplicity/actions/runs/6971043008/job/18970210995 

various hacky fixes in the vendored code, and additional failures in subsequent jobs: https://github.com/delta1/rust-simplicity/actions/workflows/main.yml 

is there someone with enough C compilation knowledge on Windows to help fix these issues in upstream code?

**Comment by uncomputable** [comment]
Hey @delta1, thanks for looking into this. No one ever compiled Simplicity for windows, so there are bound to be issues.

If the error originates in https://github.com/BlockstreamResearch/simplicity, then let's open an issue there. Let's try to compile the C library on Windows and see which errors we get. Running `make check` should be enough. The library has no dependencies, except for a compiler.

I am currently porting the Simplicity for WASM. I don't know which specific error you are getting, but if Simplicity compiles on WASM, then it should also compile on Windows :)

**Comment by delta1** [comment]
@uncomputable repro in https://github.com/BlockstreamResearch/simplicity/pull/211 

I'm not actually on windows which is why I'm going the actions route to repro here and upstream. When I can I'll dust off that old desktop PC.
