### ISSUE TITLE
Call FFI during jet execution

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#29]
Our jets should call the [C code](https://github.com/ElementsProject/simplicity) during their execution. This requires some steps:

- [ ] Merge #22 and develop the FFI further. _I've been postponing this to focus on API development._
- [ ] Write a Haskell importer that automatically generates the jet initialisation files for Rust. This will bring the Rust jets back up to date. @roconnor-blockstream said he would help us with this.
- [ ] Fix any remaining incompatibilities between C and Rust. For instance, the C code focuses a lot on Elements and might not support Bitcoin alone _(correct me if I'm wrong)_.

**Comment by sanket1729** [comment]
Addressed by #47
