### ISSUE TITLE
Notes from Tabconf

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/rust-simplicity#43]
- We should have a finalized `FinalizedCommitNode` type
- finalize() API that checks CommitNode is () -> () without any Witness
- `RedeemNode` API should accept `FinalizedCommitNode` to `Witness`. 

- `Value` should save the `Type` information
- Debug uncommented assertions in the code
- Add a comment explaining why we `Clone` in encoding `Witness`	

- Given two finalized nodes, there are two ways to compose them:
	 - _Un_finalize both of them and refinalize them again. This is the trivially correct way to do it but it may change the types of witness nodes.
	 - "Unify" the nodes. This _should?_ work if there are no cross-references. Either it fits or does not fit under unification constraints. 
	 - Can we say under what conditions the second approach is the correct way to do things? Should we refuse to unify if the second approach is not the same as the first?

**Comment by apoelstra** [comment]
cc @roconnor-blockstream the last bullet point in particular we had some doubts about and would've liked to have had you in the room. (We can also have a phone call to try to elaborate if it's not clear from this issue what we're thinking.)

**Comment by uncomputable** [comment]
I think we should split this into separate issues and those this one.

**Comment by uncomputable** [comment]
Moved to #105 #106 #107 #108
