### ISSUE TITLE
Should we re-add `amr` to test that the type inference is consistent?

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/rust-simplicity#54]
To recall `amr`, this is Hash(imr, source_type, target_type). This is not only useful in directly checking sharing, but also useful for cross testing that our type inference is consistent with C implementation. 

Now that we have a good FFI, we could also be using `test_program` for testing execution, cmr, amr and imr computations. 

```C
static void test_program(
char* name, const unsigned char* program, 
size_t program_len,
bool expectedResult,
const uint32_t* expectedCMR,
const uint32_t* expectedIMR,
const uint32_t* expectedAMR
) {
```

**Comment by uncomputable** [comment]
I don't see why we shouldn't add the AMR. It was removed because it was old obscure code, but now we know how we want to use it. [We are already implicitly using it for sharing](https://github.com/ElementsProject/rust-simplicity/blob/master/src/sharing.rs#L24).

If you want, I could write up a PR.

**Comment by apoelstra** [comment]
Agreed -- let's bring it back. I'm sure we won't be the only ones doing our own implementation who would like this cross-check.
