### ISSUE TITLE
Replace Rc with Arc

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#86]
We have a lot of `Rc`s and they are not thread-safe. We can use this issue to track the places where we want to use `Arc` instead.

**Comment by apoelstra** [comment]
Basically nothing we publicly export should contain any `Rc`s in them.

As a first approximation we should just replace literally every `Rc` with `Arc`.

**Comment by uncomputable** [comment]
I don't find a single use of `Rc` on `master`. #145 removed them all it seems.
