### ISSUE TITLE
Remove ? operators that cannot fail

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#89]
There are many impossible error paths in `CommitNode` [constructors](https://github.com/BlockstreamResearch/rust-simplicity/blob/291eb80d8374c6c34f4942be4b251e790f981fc8/src/core/commit.rs#L581) and in the [compiler](https://github.com/BlockstreamResearch/rust-simplicity/blob/291eb80d8374c6c34f4942be4b251e790f981fc8/src/policy/compiler.rs#L183). In the general case, these combinators could fail, but in these specific cases they cannot. We should replace `?` with `expect`.

**Comment by apoelstra** [comment]
I think the last of these were removed in #143 which revamped the compiler/satisfier.
