### ISSUE TITLE
More efficient word jet CMR

### ISSUE THREAD

**Issue by uncomputable** [BlockstreamResearch/rust-simplicity#90]
The CMR of a word jet is the same as the IMR of the equivalent scribe expression.

Currently we literally construct the scribe tree and compute the IMR. There exists an [inline algorithm](https://github.com/BlockstreamResearch/simplicity/blob/a365c82347a61b5300a9b02d6f6adb4b7bccaeae/C/dag.c#L80-L136) which is more efficient.

- [x] Check if naive construction and inline algorithm are equivalent
- [x] Replace naive construction with inline algorithm

**Comment by apoelstra** [comment]
For the first bullet point, since the current algorithm can be done via the public API (I think) we can add a fuzz test which checks equality.
