### ISSUE TITLE
no way to decode program

### ISSUE THREAD

**Issue by apoelstra** [BlockstreamResearch/rust-simplicity#94]
It appears that there is no canonical way to decode a program as a `CommitNode`; the `decode_program_fresh_witness` function is private.

Also, despite having "program" in the name, it does not check that the decoded node is 1->1. It should.

**Comment by apoelstra** [comment]
Also `decode_program_fresh_witness` crashes if you give it the hex `"3f0000ff0100000000000000000000001f0200000000000000db00000000000000050700"`.

**Comment by uncomputable** [comment]
We added this functionality to hal-simplicity a while back, using unit values as placeholders in the witness. [I removed it today](https://github.com/uncomputable/hal-simplicity/commit/ea60623fa5dd79d05a9f02248d68b56ebcf143e4), but we could add it back into rust-simplicity,

**Comment by apoelstra** [comment]
In #97 I fixed the issue, but I am going to do a followup PR that eliminates this logic entirely.

**Comment by uncomputable** [comment]
Isn't the canonical way `CommitNode::decode()`?

**Comment by uncomputable** [comment]
This relates to #43 that we have no concept of "program" in the code as an "expression" of type `1 → 1`. I'm not sure if it makes sense to decode arbitrary expressions. We could open another issue with the explicit goal of separating expressions from programs.

**Comment by apoelstra** [comment]
Near the bottom of #99 (which I should maybe split into multiple PRs) I add a `decode_program` method which basically just does `CommitNode::decode` followed by a typeck. I think having that method is all the "program" support that we need, and that that PR would close this issue.

**Comment by uncomputable** [comment]
Resolved by #99
